version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - ACCESS_TOKEN_EXPIRE_MINUTES=15
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - SECRET_KEY=oGZGMadkunyMgtSxgV8dFg2UWkaqxYUvopvsvK7axrm61UekefE7mQrhQLJTt37E
      - ALGORITHM=HS256
      - DATABASE_URL=postgresql+asyncpg://authdb_owner:0MFqZ9rjyEUX@ep-falling-dust-a1nu2soz-pooler.ap-southeast-1.aws.neon.tech/authdb?sslmode=require
      - AUTH_MODE=jwt
      - GOOGLE_CLIENT_ID=temp
      - GOOGLE_CLIENT_SECRET=temp
      - GITHUB_CLIENT_ID=temp
      - GITHUB_CLIENT_SECRET=temp
      - HINATA_HOST=temp
      - SMTP_NETCORE=temp
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
