"""Change the foreign key of refresh tokens

Revision ID: 19dcd550320a
Revises: 7c6728d31d1b
Create Date: 2025-05-31 22:44:13.928714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19dcd550320a'
down_revision: Union[str, None] = '7c6728d31d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('refresh_tokens_user_email_fkey', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_column('refresh_tokens', 'user_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_user_email_fkey', 'refresh_tokens', 'users', ['user_email'], ['email'])
    op.drop_column('refresh_tokens', 'user_id')
    # ### end Alembic commands ###
