"""Remove unique constraint from refresh token

Revision ID: 589e69df03bc
Revises: 19dcd550320a
Create Date: 2025-05-31 22:47:46.611829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589e69df03bc'
down_revision: Union[str, None] = '19dcd550320a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_tokens_token', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_index('ix_refresh_tokens_token', 'refresh_tokens', ['token'], unique=False)
    # ### end Alembic commands ###
