"""Add slug to roles

Revision ID: 8c66f6d691dc
Revises: 043179d5cb1b
Create Date: 2025-05-15 17:13:49.141470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c66f6d691dc'
down_revision: Union[str, None] = '043179d5cb1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_permissions_slug'), 'permissions', ['slug'], unique=True)
    op.add_column('roles', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_column('roles', 'slug')
    op.drop_index(op.f('ix_permissions_slug'), table_name='permissions')
    op.drop_column('permissions', 'slug')
    # ### end Alembic commands ###
